tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "readline", link: true
brew "autoconf"
brew "automake"
brew "awscli"
brew "bash"
brew "cmake"
brew "coffeescript"
brew "coreutils"
brew "pkg-config"
brew "crystal"
brew "eigen"
brew "elixir"
brew "elm"
brew "libtool"
brew "evince"
brew "ffmpeg"
brew "findutils", args: ["with-default-names"]
brew "fish"
brew "gdb"
brew "gist"
brew "git"
brew "git-lfs"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar"
brew "gnu-which", args: ["with-default-names"]
brew "pinentry"
brew "gnupg"
brew "go"
brew "gpg-agent"
brew "gzip"
brew "htop"
brew "hub"
brew "imagemagick"
brew "keychain"
brew "less"
brew "lua"
brew "make", args: ["with-default-names"]
brew "mysql", restart_service: true
brew "nvm"
brew "openssl@1.1"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "rsync"
brew "screen"
brew "the_silver_searcher"
brew "thefuck"
brew "travis"
brew "unzip"
brew "vim"
brew "vips"
brew "watch"
brew "wget"
brew "whois"
brew "yarn"
cask "dynamodb-local"
cask "java"
